version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    restart: always
    command: gunicorn paper_robin.wsgi:application -w 2 -b :8000 --reload
    entrypoint: /code/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod.db
    depends_on:
      - db
      
volumes:
  postgres_data: