version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  redis:
    image: "redis:alpine"
  api:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    environment:
      - RUN_ENTRYPOINT=true
    depends_on:
      - db
      - redis
  celery:
    build: ./backend
    command: celery -A paper_robin worker -l info
    volumes: 
      - ./backend/:/code/
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./backend
    command: celery -A paper_robin beat -l info
    volumes:
      - ./backend/:/code/
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
      - redis
  portal:
    build: ./portal
    restart: always
    volumes:
      - './portal/:/app/'
      - './portal/app/node_modules/'
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.dev

volumes:
  postgres_data:
