version: '3'

services:
  db:
    image: postgres
  web:
    restart: always
    build: .
    command: gunicorn paper_robin.wsgi:application -w 2 -b :8000 --reload
    volumes:
      - .:/code/paper_robin
    ports:
      - "8000:8000"
    depends_on:
      - db