# Generated by Django 3.0.2 on 2020-02-29 22:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200229_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_abbr', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='exchanges',
            field=models.ManyToManyField(to='stock.StockExchange'),
        ),
    ]
