# Generated by Django 3.0.2 on 2020-02-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20200229_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexchange',
            name='timezone',
            field=models.CharField(max_length=255),
        ),
    ]
