# Generated by Django 3.0.2 on 2020-02-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20200229_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='name_abbr',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='timezone',
            field=models.CharField(max_length=50),
        ),
    ]
