# Generated by Django 3.0.2 on 2020-03-01 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200229_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_connected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
